import type { ActorDef, AnyWorld, SpriteMap, SpritePalette } from "@/engine";

/**
 * bandProps — furniture that stands INSIDE the walkable band, as one-frame
 * runtime actors.
 *
 * WHY ACTORS. Scene artwork is one SVG behind every figure; the Foreground
 * plane is in front of every figure, always. Neither can express "the player
 * walked behind the barrel". The runtime already solves this for people: in a
 * ground-band scene every actor is depth-sorted by its feet line
 * (z = 20 + y), against the player and against each other. So a barrel table
 * becomes an actor with one frame and no brain — it stands there, and the
 * sorting the engine already does for characters makes it a physical object
 * for free. The pattern costs one <div> per prop; a scene carries half a
 * dozen, not fifty — everything glued to the back line (y = 150) stays in the
 * cheap SVG planes, because the player's feet can never be behind the back
 * line and flat art there sorts correctly by construction.
 *
 * THE ART. Frames are sprite maps at cell 1, generated by small functions
 * rather than typed by hand — a cylinder's rim is math, not forty rows of
 * string literal. Conventions match the rest of the kit: light from the
 * top-left; a visible TOP FACE, because the camera sits slightly above eye
 * height (the band itself is the proof: you can see the ground plane); a
 * one-pixel lit edge on top/left surfaces and a shaded column on the right;
 * `.` is transparent.
 *
 * Every prop here expects the scene to provide, at the same coordinates:
 *   - a GroundBlocker matching its footprint, and
 *   - a cast shadow painted in the scene's ground/static plane (the shadow
 *     must render UNDER every figure, so it cannot live on the actor).
 */

/* ------------------------------------------------------------ the helper -- */

/** A standing object with one frame: the whole ActorDef, minus the brain. */
export function propActor<W extends AnyWorld>(
  id: string,
  x: number,
  y: number,
  map: SpriteMap,
  palette: SpritePalette,
  opts?: { visible?: (world: W) => boolean; facing?: 1 | -1 },
): ActorDef<W> {
  return {
    id,
    width: map[0]?.length ?? 0,
    height: map.length,
    cell: 1,
    frames: { s: map },
    palette,
    idleFrame: "s",
    x,
    y,
    facing: opts?.facing ?? 1,
    visible: opts?.visible,
  };
}

/* --------------------------------------------------------------- drawing -- */

type Grid = string[][];

function grid(w: number, h: number): Grid {
  return Array.from({ length: h }, () => Array.from({ length: w }, () => "."));
}

function toMap(g: Grid): SpriteMap {
  return g.map((row) => row.join(""));
}

function put(g: Grid, x: number, y: number, ch: string) {
  if (y >= 0 && y < g.length && x >= 0 && x < (g[0]?.length ?? 0)) g[y][x] = ch;
}

function fill(g: Grid, x: number, y: number, w: number, h: number, ch: string) {
  for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) put(g, x + i, y + j, ch);
}

/** Half-width of an ellipse of horizontal radius rx at row offset t∈[-1,1]. */
function hw(rx: number, t: number): number {
  const s = 1 - t * t;
  return s <= 0 ? 0 : Math.max(1, Math.round(rx * Math.sqrt(s)));
}

/* ------------------------------------------------------------ the barrel -- */

/**
 * A beer keg stood on end as a table: 22×44 (0.58 m wide, 1.15 m to the rim).
 * The top face is what sells the volume — an ellipse of lit steel with the
 * far rim bright and the near rim in shade — and the chime hoops wrap it,
 * bending down at the edges the way a hoop on a cylinder must.
 */
export function barrelMap(withGlasses: boolean): SpriteMap {
  const W = 22;
  const H = 44;
  const RX = 10;
  const RY = 4;
  const cx = 11;
  const g = grid(W, H);
  const topCy = RY; // ellipse centre row of the top face

  /* body: columns shaded as a cylinder — highlight band left of centre */
  for (let y = topCy; y < H; y++) {
    for (let x = cx - RX; x <= cx + RX - 1; x++) {
      const t = (x - (cx - RX)) / (2 * RX - 1); // 0..1 across the drum
      let ch = "b";
      if (t < 0.08) ch = "d";
      else if (t < 0.2) ch = "m";
      else if (t < 0.42)
        ch = "h"; // the highlight band
      else if (t < 0.72) ch = "b";
      else if (t < 0.9) ch = "m";
      else ch = "d";
      put(g, x, y, ch);
    }
  }
  /* round the drum's foot corners off */
  for (const y of [H - 1]) {
    put(g, cx - RX, y, ".");
    put(g, cx + RX - 1, y, ".");
  }

  /* hoops: two pixel bands that dip at the edges (they wrap the curve) */
  for (const hoopY of [14, 26, 38]) {
    for (let x = cx - RX; x <= cx + RX - 1; x++) {
      const t = Math.abs((x - cx + 0.5) / RX);
      const dip = t > 0.86 ? 1 : 0;
      put(g, x, hoopY + dip, "k");
      put(g, x, hoopY + dip + 1, "K");
    }
  }

  /* the top face, painted last so the rim owns its pixels */
  for (let dy = -RY; dy <= RY; dy++) {
    const w2 = hw(RX, dy / RY);
    for (let x = cx - w2; x <= cx + w2 - 1; x++) {
      const rim = x === cx - w2 || x === cx + w2 - 1 || dy === -RY || dy === RY;
      put(g, x, topCy + dy, rim ? (dy < 0 ? "h" : "K") : "t");
    }
  }
  /* the puddle of last night's beer on the top face */
  put(g, cx + 2, topCy, "T");
  put(g, cx + 3, topCy, "T");

  if (withGlasses) {
    /* two plastic cups standing on the far half of the top face */
    fill(g, cx - 5, topCy - 6, 3, 6, "c");
    put(g, cx - 5, topCy - 6, "C");
    fill(g, cx + 4, topCy - 5, 3, 5, "c");
    put(g, cx + 4, topCy - 5, "C");
  }
  return toMap(g);
}

export const BARREL_PALETTE: SpritePalette = {
  h: "#9a7a58",
  b: "#86664a",
  m: "#795c42",
  d: "#5a4433",
  t: "#8d6f52", // the top face, a touch flatter than the highlight
  T: "#6a503a", // the beer ring
  k: "#4c3a2b", // hoop
  K: "#3a2d22", // hoop shadow edge
  c: "#e8e2d2", // cup
  C: "#fff6e0", // cup highlight
};

/* ------------------------------------------------------- the picnic table -- */

/**
 * The A-frame picnic table, 58×30, seen from the walk: far bench as a thin
 * lit strip beyond the top, the tabletop as a real plank face, the near bench
 * low and wide in front, X-legs at the ends. Three depths in one object,
 * which is the whole reason to look at it.
 */
export function picnicMap(): SpriteMap {
  const W = 58;
  const H = 30;
  const g = grid(W, H);

  /* far bench: a strip at the very top, mostly hidden by the tabletop */
  fill(g, 6, 0, 46, 2, "m");
  fill(g, 6, 0, 46, 1, "b");

  /* tabletop: top face, three planks with gaps, then the front edge */
  fill(g, 2, 3, 54, 6, "b");
  fill(g, 2, 3, 54, 1, "h");
  for (const gap of [5, 7]) fill(g, 3, gap, 52, 1, "m");
  fill(g, 2, 9, 54, 2, "l");
  fill(g, 2, 11, 54, 1, "d");

  /* the X legs at both ends, stepped diagonals */
  for (let i = 0; i < 12; i++) {
    put(g, 6 + i, 12 + i, "l");
    put(g, 7 + i, 12 + i, "l");
    put(g, 17 - i, 12 + i, "m");
    put(g, 18 - i, 12 + i, "m");
    put(g, 40 + i, 12 + i, "l");
    put(g, 41 + i, 12 + i, "l");
    put(g, 51 - i, 12 + i, "m");
    put(g, 52 - i, 12 + i, "m");
  }

  /* near bench: seat face + front edge, low across the whole front */
  fill(g, 0, 21, 58, 3, "b");
  fill(g, 0, 21, 58, 1, "h");
  fill(g, 0, 24, 58, 2, "l");
  /* its legs */
  fill(g, 4, 26, 3, 4, "d");
  fill(g, 51, 26, 3, 4, "d");

  /* somebody's bottle on the tabletop */
  fill(g, 34, 0, 2, 4, "g");
  put(g, 34, 0, "G");
  return toMap(g);
}

export const PICNIC_PALETTE: SpritePalette = {
  h: "#a8804f",
  b: "#8a623f",
  m: "#6b4a2f",
  l: "#5d4029",
  d: "#42301f",
  g: "#3f6f52",
  G: "#5c8f6e",
};

/* ------------------------------------------------------------- the kosz --- */

/** The little green street bin, 14×24 — a cylinder on a post collar. */
export function koszMap(): SpriteMap {
  const W = 14;
  const H = 24;
  const g = grid(W, H);
  /* drum */
  for (let y = 2; y < 18; y++) {
    for (let x = 1; x < 13; x++) {
      const t = (x - 1) / 11;
      put(g, x, y, t < 0.15 ? "m" : t < 0.4 ? "h" : t < 0.75 ? "b" : "m");
    }
  }
  /* mouth: dark opening with a lit far lip */
  for (let x = 2; x < 12; x++) {
    put(g, x, 1, "h");
    put(g, x, 2, "o");
    put(g, x, 3, "o");
  }
  put(g, 2, 2, "m");
  put(g, 11, 2, "m");
  /* band + the bag peeking over the rim */
  fill(g, 1, 8, 12, 1, "l");
  put(g, 4, 1, "w");
  put(g, 5, 1, "w");
  /* post */
  fill(g, 6, 18, 3, 6, "l");
  fill(g, 6, 18, 1, 6, "m");
  return toMap(g);
}

export const KOSZ_PALETTE: SpritePalette = {
  h: "#4a8a5a",
  b: "#3a7048",
  m: "#2e5c3b",
  l: "#24482f",
  o: "#12140f",
  w: "#e8e2d2",
};

/* ------------------------------------------------------------ the crates -- */

/** Two bottle crates, offset stack, 30×24 — top faces open, necks showing. */
export function cratesMap(): SpriteMap {
  const W = 30;
  const H = 24;
  const g = grid(W, H);
  const crate = (x: number, y: number, w: number) => {
    /* top face */
    fill(g, x, y, w, 3, "m");
    fill(g, x, y, w, 1, "h");
    /* bottle tops in the cells */
    for (let i = x + 2; i < x + w - 2; i += 4) {
      put(g, i, y + 1, "g");
      put(g, i + 1, y + 1, "g");
    }
    /* front face with the hand slot */
    fill(g, x, y + 3, w, 8, "b");
    fill(g, x, y + 3, 1, 8, "h");
    fill(g, x + w - 1, y + 3, 1, 8, "d");
    fill(g, x + Math.floor(w / 2) - 3, y + 5, 6, 2, "d");
    fill(g, x, y + 10, w, 1, "d");
  };
  crate(6, 0, 20); // the top crate, pushed back
  crate(0, 12, 24); // the bottom crate
  return toMap(g);
}

export const CRATES_PALETTE: SpritePalette = {
  h: "#a85850",
  b: "#8a4038",
  m: "#763830",
  d: "#4e2622",
  g: "#3f6f52",
};

/* ---------------------------------------------------------- the drum table -- */

/**
 * A cable drum on its end, 32×26 — the street's found furniture. The top is
 * one big plank disc, which is the most top-face any object here has.
 */
export function drumMap(): SpriteMap {
  const W = 32;
  const H = 26;
  const RX = 15;
  const RY = 5;
  const cx = 16;
  const g = grid(W, H);
  /* the side: slats under the disc */
  for (let y = RY; y < H; y++) {
    for (let x = cx - RX + 1; x <= cx + RX - 2; x++) {
      const t = (x - (cx - RX)) / (2 * RX - 1);
      put(g, x, y, t < 0.2 ? "m" : t < 0.5 ? "b" : t < 0.8 ? "m" : "l");
    }
  }
  for (const sx of [6, 12, 19, 25]) {
    for (let y = RY + 1; y < H - 1; y++) put(g, sx, y, "d");
  }
  /* the disc */
  for (let dy = -RY; dy <= RY; dy++) {
    const w2 = hw(RX, dy / RY);
    for (let x = cx - w2; x <= cx + w2 - 1; x++) {
      const rim = x === cx - w2 || x === cx + w2 - 1 || dy === -RY || dy === RY;
      put(g, x, RY + dy, rim ? (dy < 0 ? "h" : "d") : "t");
    }
  }
  /* plank joints across the disc, and the axle hole */
  for (let x = cx - 12; x <= cx + 11; x++) {
    put(g, x, RY - 2, "T");
    put(g, x, RY + 2, "T");
  }
  fill(g, cx - 2, RY - 1, 4, 2, "d");
  /* wax drips from last week's candle */
  put(g, cx + 8, RY - 1, "w");
  put(g, cx + 8, RY, "w");
  return toMap(g);
}

export const DRUM_PALETTE: SpritePalette = {
  h: "#a8804f",
  b: "#8a623f",
  m: "#7d5836",
  l: "#6b4a2f",
  d: "#42301f",
  t: "#96703f",
  T: "#6b4a2f",
  w: "#e8e2d2",
};

/* ----------------------------------------------------------- the A-board --- */

/** The chalk A-board, 26×32, set at a slight angle: face + returning side. */
export function aboardMap(): SpriteMap {
  const W = 26;
  const H = 32;
  const g = grid(W, H);
  /* the returning side wedge on the right — the board is an A, not a card */
  for (let y = 2; y < 30; y++) {
    const wdt = 2 + Math.floor((y - 2) / 9);
    fill(g, 20, y, wdt, 1, "l");
  }
  /* the face */
  fill(g, 0, 0, 20, 30, "b");
  fill(g, 0, 0, 20, 1, "h");
  fill(g, 0, 0, 1, 30, "m");
  fill(g, 19, 0, 1, 30, "d");
  /* the blackboard inset */
  fill(g, 2, 3, 16, 24, "o");
  /* chalk lines — tonight's names */
  fill(g, 4, 6, 12, 2, "w");
  fill(g, 4, 11, 9, 2, "w");
  fill(g, 4, 16, 11, 2, "w");
  fill(g, 4, 21, 7, 2, "w");
  /* feet */
  fill(g, 1, 30, 4, 2, "d");
  fill(g, 15, 30, 4, 2, "d");
  fill(g, 21, 30, 4, 2, "d");
  return toMap(g);
}

export const ABOARD_PALETTE: SpritePalette = {
  h: "#4a4d52",
  b: "#3a3d42",
  m: "#33363b",
  l: "#2b2e32",
  d: "#1f2226",
  o: "#17191d",
  w: "#e8e2d2",
};

/* ------------------------------------------------------- the PKP trolley -- */

/**
 * The platform barrow, 40×34 — PKP property since before anyone asked. A flat
 * bed on two spoked wheels with an upright handle, parked mid-platform at the
 * angle of something abandoned rather than placed. The bed's top face carries
 * one strapped bundle, because an empty trolley is a prop and a loaded one is
 * a job someone walked away from.
 */
export function trolleyMap(): SpriteMap {
  const W = 40;
  const H = 34;
  const g = grid(W, H);
  /* the handle, upright at the left end */
  fill(g, 3, 0, 2, 18, "m");
  fill(g, 1, 0, 6, 2, "h");
  /* the bed: top face, then the frame edge */
  fill(g, 2, 16, 36, 3, "h");
  fill(g, 2, 19, 36, 3, "b");
  fill(g, 2, 22, 36, 2, "d");
  /* the bundle on the bed, strapped twice */
  fill(g, 12, 8, 16, 8, "s");
  fill(g, 12, 8, 16, 1, "S");
  fill(g, 15, 8, 2, 8, "k");
  fill(g, 23, 8, 2, 8, "k");
  /* two spoked wheels */
  for (const cx of [10, 30]) {
    for (let dy = -5; dy <= 5; dy++) {
      const w2 = hw(5, dy / 5);
      for (let x = cx - w2; x <= cx + w2 - 1; x++) {
        const rim = x === cx - w2 || x === cx + w2 - 1 || Math.abs(dy) === 5;
        put(g, x, 28 + dy, rim ? "d" : "m");
      }
    }
    put(g, cx - 1, 27, "k");
    put(g, cx, 28, "k");
    put(g, cx - 4, 28, "k");
    put(g, cx + 3, 28, "k");
  }
  return toMap(g);
}

export const TROLLEY_PALETTE: SpritePalette = {
  h: "#8f9299",
  b: "#7a7d84",
  m: "#5d6066",
  d: "#3a3d42",
  k: "#26282c",
  s: "#8a7a58",
  S: "#a89468",
};

/* ------------------------------------------------------- the left suitcase -- */

/** A hard-shell case, 16×20, waiting more patiently than its owner did. */
export function suitcaseMap(): SpriteMap {
  const W = 16;
  const H = 20;
  const g = grid(W, H);
  fill(g, 1, 4, 14, 15, "b");
  fill(g, 1, 4, 14, 1, "h");
  fill(g, 1, 4, 1, 15, "m");
  fill(g, 14, 4, 1, 15, "d");
  /* the ribs a hard shell has */
  fill(g, 4, 5, 1, 13, "d");
  fill(g, 11, 5, 1, 13, "d");
  /* handle, and the airline sticker nobody peels */
  fill(g, 6, 1, 4, 3, "d");
  fill(g, 7, 2, 2, 2, ".");
  fill(g, 6, 9, 4, 3, "w");
  fill(g, 18, 18, 2, 2, "d");
  return toMap(g);
}

export const SUITCASE_PALETTE: SpritePalette = {
  h: "#7a5a66",
  b: "#684a56",
  m: "#573d48",
  d: "#3a2830",
  w: "#e8e2d2",
};
